before_script:
  - hostname
  - whoami
  - pwd
  - ls -la

stages:
   - build
   - test
   - coverage
   - deploy

   
build:
  tags:
     - ece651
  stage: build
  script:
    - gradle --build

test:
  tags:
     - ece651
  stage: test
  script:
    - gradle check
  artifacts:
    paths:
      - coverage
      
pages:
 stage: coverage
 tags:
     - ece651
 dependencies:
   - test
 script:
   - mv coverage public/
 artifacts:
   paths:
     - public
     
deploy:
  tags:
    - ece651
  stage: deploy
  script:
    - echo "Deploy."

