before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:
   - build
   - test
   - coverage
   - deploy

   
build:
  tags:
     - ece651
  stage: build

test:
  tags:
     - ece651
  stage: test
  artifacts:
    paths:
      - coverage
      
pages:
 stage: coverage
 tags:
     - ece651
 dependencies:
   - test
 script:
   - mv coverage public/
 artifacts:
   paths:
     - public
deploy:
  tags:
    - ece651
  stage: deploy
