/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;


public class App extends Application {

    static AnchorPane root;
    LoginView loginView;
    EnterGameView enterGameView;
    ChooseRoomView chooseRoomView;

    public App() {
        this.root = new AnchorPane();
        this.loginView = new LoginView();
        this.enterGameView = new EnterGameView();
        this.chooseRoomView = new ChooseRoomView();
    }

    public static void main(String[] args) {
//      try {
//        Client client = new Client("127.0.0.1", 12345,
//                new BufferedReader(new InputStreamReader(System.in)), System.out);
//        client.connectToServer();
//        client.login();
//        client.answerInfo();
//        client.recvNameAndSeq();
//        client.recvStartStatus();
//        if (client.getStartStatus() == 1) {
//          client.recvAssignTerritory();
//        }
//        while(true) {
//          if (!client.recvBoardPromptAndSend()) {
//            break;
//          }
//        }
//        if (client.exitOrContinue()) {
//          client.recvMsg();
//        }
//        client.closeConnection();
//      } catch (IOException e) {
//        e.printStackTrace();
//      }
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        // connect to server
        Client client = new Client("127.0.0.1", 12345,
                new BufferedReader(new InputStreamReader(System.in)), System.out);
        client.connectToServer();

        // login
        loginView.init();
        root.getChildren().add(loginView.loginPane);
        LoginController loginController = new LoginController(loginView, enterGameView, client);

        // set scene
        Scene scene = new Scene(root, 1500, 800);
        primaryStage.setTitle("Welcome to RISC");
        primaryStage.setScene(scene);
        primaryStage.show();

    }
}
