/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import java.io.IOException;

public class App {
    
    public static void main(String[] args) {
      try {
        Server server = new Server(12345);
        while(true) {
          System.out.println("Start to accept...");
          server.assignRoom();
        }
      } catch (IOException e) {
        e.printStackTrace();
      } 
    }
}
